# Generated by Django 4.1.3 on 2022-11-07 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('dorm_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('dorm_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('width', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('string_no', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=False, verbose_name='Zoning Fee')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_.person')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_.person'),
        ),
    ]
