# Generated by Django 4.1.3 on 2022-11-27 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_', '0002_club_person_play_club_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='width',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='team_pic',
            field=models.ImageField(blank=True, default='defaultimg.png', null=True, upload_to='', verbose_name='Team Image'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='play',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='baseball_.person'),
        ),
        migrations.AlterField(
            model_name='play',
            name='string_no',
            field=models.CharField(choices=[('First String', 'First String'), ('Second String', 'Second String')], max_length=100),
        ),
        migrations.AlterField(
            model_name='play',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='baseball_.club'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_t1', models.IntegerField()),
                ('score_t2', models.IntegerField()),
                ('game_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Issuance')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='baseball_.club')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='baseball_.club')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='baseball_.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
